doBar – PlPlotLib
doBar Subroutine
Source File
subroutine doBar()
Arguments
None
Description
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: N = 21
real(kind=wp), public, dimension(N) :: x
real(kind=wp), public, dimension(N) :: y
Source Code
    subroutine doBar
        !! ![bar](|media|/example-6.svg)
        integer,parameter::N = 21
        real(wp),dimension(N)::x,y
        x = linspace(-PI,PI,N)
        y = exp(-x**2)
        call figure()
        call subplot(1,2,1)
        call xylim(mixval(x)+[-0.1_wp,0.1_wp],mixval(y)+[ 0.0_wp,0.1_wp])
        call bar(x,y,c=y,relWidth=1.0_wp)
        call ticks()
        call labels('x','y','')
        call subplot(1,2,2)
        call xylim(mixval(y)+[ 0.0_wp,0.1_wp],mixval(x)+[-0.1_wp,0.1_wp])
        call barh(x,y,fillColor='r',relWidth=1.0_wp)
        call ticks()
        call labels('x','y','')
    end subroutine doBar
Call graph
dobar calls linspace, mixval, ticks, xylim, subplot, figure, barh, bar, labels
ticks calls plbox
xylim calls plwind
subplot calls plvsta, plssub, plvasp, plvpor, pladv
figure calls plssub, pladv, pleop, plbop
barh calls mixval, plline, plfill, plcol1
bar calls mixval, plline, plfill, plcol1
labels calls pllab
examples_prg calls dobar