doContour – PlPlotLib
doContour Subroutine
Source File
Variables
N x y z i j
Source Code
doContour
All Procedures
bar barh binData box colorbar colorbar2 colorize contour contourf doBar doContour doError doExamples doFillBetween doHist doLegend doPlot doQuiver doScatter doSurface endsWith errorbar figure fillBetween fillBetweenx flatten hist int2char labels legend linspace makeLogo mean meshGridX meshGridY mixval plot plot3 printTypes quiver randomNormal randomUniform real2char scatter setup show showProgress span startsWith stdev subplot surface ticks title wireframe xlabel xlim xticks xylim xyzlim ylabel ylim yticks
public subroutine doContour()
Arguments
None
Description
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: N = 50
real(kind=wp), public, dimension(N) :: x
real(kind=wp), public, dimension(N) :: y
real(kind=wp), public, dimension(N,N) :: z
integer, public :: i
integer, public :: j
Source Code
    subroutine doContour
        !! ![contour](|media|/example-3.svg)
        integer,parameter::N = 50
        real(wp),dimension(N)::x,y
        real(wp),dimension(N,N)::z
        integer::i,j
        x = linspace(-10.0_wp,10.0_wp,N)
        y = linspace(-10.0_wp,10.0_wp,N)
        forall(i=1:N,j=1:N)
            z(i,j) = sin( sqrt(x(i)**2+y(j)**2) )/sqrt(x(i)**2+y(j)**2)
        end forall
        call figure()
        call subplot(1,1,1,aspect=1.0_wp)
        call xylim(mixval(x),mixval(y))
        call contourf(x,y,z,10)
        call contour(x,y,z,10)
        call colorbar(z,5)
        call ticks()
        call labels('x','y','')
    end subroutine doContour
Call graph
docontour calls contour, colorbar, linspace, mixval, xylim, labels, contourf, subplot, figure, ticks
contour calls plcont
colorbar calls plcolorbar
xylim calls plwind
labels calls pllab
contourf calls linspace, plshades
subplot calls plvpor, plvsta, plvasp, plssub, pladv
figure calls plssub, pladv, pleop, plbop
ticks calls plbox
doexamples calls docontour
main_prg calls doexamples