doError – PlPlotLib
doError Subroutine
Source File
Variables
N x y xe ye r m s k
Source Code
doError
All Procedures
bar barh binData box colorbar colorbar2 colorize contour contourf doBar doContour doError doExamples doFillBetween doHist doLegend doPlot doQuiver doScatter doSurface endsWith errorbar figure fillBetween fillBetweenx flatten hist int2char labels legend linspace makeLogo mean meshGridX meshGridY mixval plot plot3 printTypes quiver randomNormal randomUniform real2char scatter setup show showProgress span startsWith stdev subplot surface ticks title wireframe xlabel xlim xticks xylim xyzlim ylabel ylim yticks
public subroutine doError()
Arguments
None
Description
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: N = 25
real(kind=wp), public, dimension(N) :: x
real(kind=wp), public, dimension(N) :: y
real(kind=wp), public, dimension(N) :: xe
real(kind=wp), public, dimension(N) :: ye
real(kind=wp), public, dimension(12) :: r
real(kind=wp), public :: m
real(kind=wp), public :: s
integer, public :: k
Source Code
    subroutine doError
        !! ![error](|media|/example-10.svg)
        integer,parameter::N = 25
        real(wp),dimension(N)::x,y,xe,ye
        real(wp),dimension(12)::r
        real(wp)::m,s
        integer::k
        x = linspace(0.0_wp,5.0_wp,N)
        y = 1.0_wp/(x**2+1.0_wp)
        do k=1,N
            call random_number(r)
            r = 0.25_wp*(2.0_wp*r-1.0_wp)
            m = sum(r)/real(size(r))
            s = sqrt(sum((r-m)**2)/real(size(r)-1))
            x(k) = x(k)+m
            xe(k) = s
            call random_number(r)
            r = 0.15_wp*(2.0_wp*r-1.0_wp)
            m = sum(r)/real(size(r))
            s = sqrt(sum((r-m)**2)/real(size(r)-1))
            y(k) = y(k)+m
            ye(k) = s
        end do
        call figure()
        call subplot(1,1,1)
        call xylim(mixval([x-xe,x+xe])+[-0.5_wp,0.5_wp],mixval([y-ye,y+ye])+[-0.2_wp,0.2_wp])
        call errorbar(x,y,xerr=xe,yerr=ye,lineColor='b',lineWidth=1.0_wp)
        call plot(x,y,lineStyle='',markStyle='s',markColor='r',markSize=1.5_wp)
        call ticks()
        call labels('x','y','')
    end subroutine doError
Call graph
doerror calls linspace, mixval, xylim, plot, figure, subplot, errorbar, ticks, labels
xylim calls plwind
plot calls plptex, plline, plssym
figure calls pladv, pleop, plssub, plbop
subplot calls pladv, plssub, plvpor, plvsta, plvasp
errorbar calls plerrx, plerry
ticks calls plbox
labels calls pllab
doexamples calls doerror
main_prg calls doexamples