doExamples – PlPlotLib
doExamples Subroutine
Source File
Source Code
doExamples
All Procedures
bar barh binData box colorbar colorbar2 colorize contour contourf doBar doContour doError doExamples doFillBetween doHist doLegend doPlot doQuiver doScatter doSurface endsWith errorbar figure fillBetween fillBetweenx flatten hist int2char labels legend linspace makeLogo mean meshGridX meshGridY mixval plot plot3 printTypes quiver randomNormal randomUniform real2char scatter setup show showProgress span startsWith stdev subplot surface ticks title wireframe xlabel xlim xticks xylim xyzlim ylabel ylim yticks
public subroutine doExamples()
Arguments
None
Calls
Called By
Source Code
    subroutine doExamples
        call doPlot()
        call doScatter()
        call doContour()
        call doLegend()
        call doQuiver()
        call doBar()
        call doFillBetween()
        call doHist()
        call doSurface()
        call doError()
    end subroutine doExamples
Call graph
doexamples calls doerror, doplot, doscatter, dolegend, docontour, dohist, dobar, dosurface, doquiver, dofillbetween
doerror calls linspace, mixval, xylim, plot, figure, subplot, errorbar, ticks, labels
doplot calls linspace, mixval, xylim, plot, figure, subplot, xlabel, ylabel, xticks, yticks, title
doscatter calls xylim, figure, subplot, ticks, labels, scatter
dolegend calls linspace, mixval, xylim, plot, figure, subplot, ticks, labels, legend
docontour calls linspace, mixval, xylim, figure, subplot, ticks, labels, contour, colorbar, contourf
dohist calls mixval, xylim, figure, subplot, ticks, bindata, hist, bar
dobar calls linspace, mixval, xylim, figure, subplot, ticks, labels, bar, barh
dosurface calls linspace, mixval, figure, subplot, xyzlim, surface, box
doquiver calls linspace, mixval, xylim, figure, subplot, ticks, labels, colorbar, quiver
dofillbetween calls linspace, mixval, xylim, plot, figure, subplot, ticks, labels, fillbetween
xylim calls plwind
plot calls plptex, plline, plssym
figure calls pladv, pleop, plssub, plbop
subplot calls pladv, plssub, plvpor, plvsta, plvasp
errorbar calls plerrx, plerry
ticks calls plbox
labels calls pllab
xlabel calls plmtex
ylabel calls plmtex
xticks calls plbox
yticks calls plbox
title calls plmtex
scatter calls mixval, plptex, plssym, plschr, plcol1
legend calls pllegend, domarkers, doboxes, dolegendbox, dolines, dotext
contour calls plcont
colorbar calls plcolorbar
contourf calls linspace, plshades
bindata calls linspace
hist calls mixval, bindata, bar
bar calls mixval, plline, plcol1, plfill
barh calls mixval, plline, plcol1, plfill
xyzlim calls plwind, plw3d
surface calls linspace, plsurf3d
box calls plbox3
quiver calls mixval, plcol1, plvect
fillbetween calls plfill
main_prg calls doexamples