doFillBetween – PlPlotLib
doFillBetween Subroutine
Source File
Variables
N x y1 y2
Source Code
doFillBetween
All Procedures
bar barh binData box colorbar colorbar2 colorize contour contourf doBar doContour doError doExamples doFillBetween doHist doLegend doPlot doQuiver doScatter doSurface endsWith errorbar figure fillBetween fillBetweenx flatten hist int2char labels legend linspace makeLogo mean meshGridX meshGridY mixval plot plot3 printTypes quiver randomNormal randomUniform real2char scatter setup show showProgress span startsWith stdev subplot surface ticks title wireframe xlabel xlim xticks xylim xyzlim ylabel ylim yticks
public subroutine doFillBetween()
Arguments
None
Description
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: N = 51
real(kind=wp), public, dimension(N) :: x
real(kind=wp), public, dimension(N) :: y1
real(kind=wp), public, dimension(N) :: y2
Source Code
    subroutine doFillBetween
        !! ![fillBetween](|media|/example-7.svg)
        integer,parameter::N = 51
        real(wp),dimension(N)::x,y1,y2
        x = linspace(-3.0_wp,3.0_wp,N)
        y1 = x**2-1.0_wp
        y2 = x**3-1.0_wp
        call figure()
        call subplot(1,1,1)
        call xylim(mixval(x),mixval([y1,y2]))
        call fillBetween(x,y1,y2,fillColor='c',fillPattern='\',lineWidth=2.0_wp)
        call plot(x,y1,lineColor='k',lineWidth=3.0_wp)
        call plot(x,y2,lineColor='k',lineWidth=3.0_wp)
        call ticks(color='b',lineWidth=3.0_wp)
        call labels('x','y','f(x)=x#u2#d-1',color='r')
    end subroutine doFillBetween
Call graph
dofillbetween calls linspace, fillbetween, mixval, plot, labels, xylim, subplot, figure, ticks
fillbetween calls plfill
plot calls plptex, plline, plssym
labels calls pllab
xylim calls plwind
subplot calls plvpor, plvsta, plvasp, plssub, pladv
figure calls plssub, pladv, pleop, plbop
ticks calls plbox
doexamples calls dofillbetween
main_prg calls doexamples