doHist – PlPlotLib
doHist Subroutine
Source File
subroutine doHist()
Arguments
None
Description
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: N = 10000
real(kind=wp), public, dimension(N,12) :: r
real(kind=wp), public, dimension(N) :: x
real(kind=wp), public, dimension(:,:), allocatable :: h
Source Code
    subroutine doHist
        !! ![hist](|media|/example-8.svg)
        integer,parameter::N = 10000
        real(wp),dimension(N,12)::r
        real(wp),dimension(N)::x
        real(wp),dimension(:,:),allocatable::h
        call random_number(r)
        x = sum(r,2)-6.0_wp
        call figure()
        call subplot(1,2,1)
        call xylim(mixval(x),[0.0_wp,1.05_wp])
        call hist(x,20)
        call ticks()
        h = binData(x,20,normalize=2)
        call subplot(1,2,2)
        call xylim(mixval(h(:,1)),[0.0_wp,1.05_wp*maxval(h(:,2))])
        call bar(h(:,1),h(:,2),c=h(:,2),relWidth=1.0_wp)
        call ticks()
    end subroutine doHist
Call graph
dohist calls hist, ticks, xylim, bar, mixval, bindata, figure, subplot
hist calls bar, mixval, bindata
ticks calls plbox
xylim calls plwind
bar calls mixval, plline, plcol1, plfill
bindata calls linspace
figure calls pleop, plbop, pladv, plssub
subplot calls pladv, plssub, plvasp, plvsta, plvpor
examples_prg calls dohist