doLegend – PlPlotLib
doLegend Subroutine
Source File
Variables
N x y series
Source Code
doLegend
All Procedures
bar barh binData box colorbar colorbar2 colorize contour contourf doBar doContour doError doExamples doFillBetween doHist doLegend doPlot doQuiver doScatter doSurface endsWith errorbar figure fillBetween fillBetweenx flatten hist int2char labels legend linspace makeLogo mean meshGridX meshGridY mixval plot plot3 printTypes quiver randomNormal randomUniform real2char scatter setup show showProgress span startsWith stdev subplot surface ticks title wireframe xlabel xlim xticks xylim xyzlim ylabel ylim yticks
public subroutine doLegend()
Arguments
None
Description
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: N = 20
real(kind=wp), public, dimension(N) :: x
real(kind=wp), public, dimension(N) :: y
character(len=32), public, dimension(3,7) :: series
Source Code
    subroutine doLegend
        !! ![legend](|media|/example-4.svg)
        integer,parameter::N = 20
        real(wp),dimension(N)::x,y
        character(32),dimension(3,7)::series
        x = linspace(0.0_wp,1.0_wp,N)
        y = x**2-1.0_wp
        call figure()
        call subplot(1,1,1)
        call xylim(mixval(x),mixval(y))
        call plot(x,y,lineColor='red',lineWidth=2.0_wp, &
            & markStyle='.',markColor='cyan',markSize=2.0_wp)
        call plot(x,-1.0_wp-y,lineColor='blue',lineStyle=':',lineWidth=2.0_wp, &
            & markStyle='+',markColor='green',markSize=1.0_wp)
        ! [name,textColor,lineStyle,lineColor,markStyle,markColor]
        series(1,:) = [character(32)::'f(x)=x#u2#d-1','','-','r','.','c','']
        series(2,:) = [character(32)::'g(x)=-x#u2#d','',':','b','+','g','']
        series(3,:) = [character(32)::'Box','','','','','','r']
        call legend('center left',series)
        call ticks()
        call labels('x','y','')
    end subroutine doLegend
Call graph
dolegend calls linspace, mixval, xylim, plot, labels, legend, subplot, figure, ticks
xylim calls plwind
plot calls plptex, plline, plssym
labels calls pllab
legend calls pllegend, domarkers, doboxes, dolegendbox, dolines, dotext
subplot calls plvpor, plvsta, plvasp, plssub, pladv
figure calls plssub, pladv, pleop, plbop
ticks calls plbox
doexamples calls dolegend
main_prg calls doexamples