doLogPlot – PlPlotLib
doLogPlot Subroutine
Source File
subroutine doLogPlot()
Arguments
None
Description
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: N = 25
real(kind=wp), public, dimension(N) :: x
real(kind=wp), public, dimension(N) :: y
real(kind=wp), public, dimension(N) :: yl
Source Code
    subroutine doLogPlot
        !! ![logPlot](|media|/example-11.svg)
        integer,parameter::N = 25
        real(wp),dimension(N)::x,y,yl
        x = linspace(0.0_wp,5.0_wp,N)
        y = exp(-x**2)
        yl = log10(y)
        call figure()
        call subplot(1,1,1)
        call xylim(mixval(x),mixval(yl))
        call plot(x,yl,lineColor='r',lineWidth=2.0_wp)
        call ticks(logy=.true.)
        call labels('x [linear]','y [log]','exp(-x#u2#d)')
    end subroutine doLogPlot
Call graph
dologplot calls linspace, mixval, ticks, plot, xylim, subplot, figure, labels
ticks calls plbox
plot calls plptex, plline, plssym
xylim calls plwind
subplot calls plvsta, plssub, plvasp, plvpor, pladv
figure calls plssub, pladv, pleop, plbop
labels calls pllab
examples_prg calls dologplot