doPlot – PlPlotLib
doPlot Subroutine
Source File
subroutine doPlot()
Arguments
None
Description
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: N = 20
real(kind=wp), public, dimension(N) :: x
real(kind=wp), public, dimension(N) :: y
Source Code
    subroutine doPlot
        !! ![plot](|media|/example-1.svg)
        integer,parameter::N = 20
        real(wp),dimension(N)::x,y
        x = linspace(0.0_wp,1.0_wp,N)
        y = x**2-1.0_wp
        call figure()
        call subplot(1,1,1)
        call xylim(mixval(x),mixval(y))
        call plot(x,y,lineColor='red',lineWidth=2.0_wp, &
            & markStyle='.',markColor='cyan',markSize=2.0_wp)
        call plot(x,-1.0_wp-y,lineColor='blue',lineStyle=':',lineWidth=2.0_wp, &
            & markStyle='+',markColor='green',markSize=1.0_wp)
!~         call ticks()
        call xticks(primary=.true.,secondary=.false.)
        call yticks(primary=.true.,secondary=.false.)
!~         call labels('x','y','f(x)=x#u2#d-1; g(x)=-x#u2#d')
        call xlabel('x')
        call ylabel('y')
        call title('f(x)=x#u2#d-1; g(x)=-x#u2#d')
    end subroutine doPlot
Call graph
doplot calls title, plot, yticks, xylim, xlabel, linspace, mixval, ylabel, xticks, figure, subplot
title calls plmtex
plot calls plline, plssym, plptex
yticks calls plbox
xylim calls plwind
xlabel calls plmtex
ylabel calls plmtex
xticks calls plbox
figure calls pleop, plbop, pladv, plssub
subplot calls pladv, plssub, plvasp, plvsta, plvpor
examples_prg calls doplot