doQuiver – PlPlotLib
doQuiver Subroutine
Source File
Variables
N x y u v m i j
Source Code
doQuiver
All Procedures
bar barh binData box colorbar colorbar2 colorize contour contourf doBar doContour doError doExamples doFillBetween doHist doLegend doPlot doQuiver doScatter doSurface endsWith errorbar figure fillBetween fillBetweenx flatten hist int2char labels legend linspace makeLogo mean meshGridX meshGridY mixval plot plot3 printTypes quiver randomNormal randomUniform real2char scatter setup show showProgress span startsWith stdev subplot surface ticks title wireframe xlabel xlim xticks xylim xyzlim ylabel ylim yticks
public subroutine doQuiver()
Arguments
None
Description
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: N = 20
real(kind=wp), public, dimension(N) :: x
real(kind=wp), public, dimension(N) :: y
real(kind=wp), public, dimension(N,N) :: u
real(kind=wp), public, dimension(N,N) :: v
real(kind=wp), public, dimension(N,N) :: m
integer, public :: i
integer, public :: j
Source Code
    subroutine doQuiver
        !! ![quiver](|media|/example-5.svg)
        integer,parameter::N = 20
        real(wp),dimension(N)::x,y
        real(wp),dimension(N,N)::u,v,m
        integer::i,j
        x = linspace(-10.0_wp,10.0_wp,N)
        y = linspace(-10.0_wp,10.0_wp,N)
        forall(i=1:N,j=1:N)
            u(i,j) = -y(j)
            v(i,j) =  x(i)
            m(i,j) = sqrt(u(i,j)**2+v(i,j)**2)
        end forall
        call figure()
        call subplot(1,1,1,aspect=1.0_wp)
        call xylim(mixval(x),mixval(y))
        call quiver(x,y,u,v,c=m,s=m,scaling=2.0_wp,lineWidth=2.0_wp)
        call colorbar(m,10)
        call ticks()
        call labels('x','y','')
    end subroutine doQuiver
Call graph
doquiver calls linspace, mixval, xylim, quiver, labels, colorbar, subplot, figure, ticks
xylim calls plwind
quiver calls mixval, plvect, plcol1
labels calls pllab
colorbar calls plcolorbar
subplot calls plvpor, plvsta, plvasp, plssub, pladv
figure calls plssub, pladv, pleop, plbop
ticks calls plbox
doexamples calls doquiver
main_prg calls doexamples