doScatter – PlPlotLib
doScatter Subroutine
Source File
Variables
N x y z
Source Code
doScatter
All Procedures
bar barh binData box colorbar colorbar2 colorize contour contourf doBar doContour doError doExamples doFillBetween doHist doLegend doPlot doQuiver doScatter doSurface endsWith errorbar figure fillBetween fillBetweenx flatten hist int2char labels legend linspace makeLogo mean meshGridX meshGridY mixval plot plot3 printTypes quiver randomNormal randomUniform real2char scatter setup show showProgress span startsWith stdev subplot surface ticks title wireframe xlabel xlim xticks xylim xyzlim ylabel ylim yticks
public subroutine doScatter()
Arguments
None
Description
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: N = 100
real(kind=wp), public, dimension(N) :: x
real(kind=wp), public, dimension(N) :: y
real(kind=wp), public, dimension(N) :: z
Source Code
    subroutine doScatter
        !! ![scatter](|media|/example-2.svg)
        integer,parameter::N = 100
        real(wp),dimension(N)::x,y,z
        call random_number(x)
        call random_number(y)
        z = sqrt(x**2+y**2)
        call figure()
        call subplot(2,2,1)
        call xylim([0.0_wp,1.0_wp],[0.0_wp,1.0_wp])
        call scatter(x,y)
        call ticks()
        call labels('x','y','')
        call subplot(2,2,2)
        call xylim([0.0_wp,1.0_wp],[0.0_wp,1.0_wp])
        call scatter(x,y,c=z)
        call ticks()
        call labels('x','y','')
        call subplot(2,2,3)
        call xylim([0.0_wp,1.0_wp],[0.0_wp,1.0_wp])
        call scatter(x,y,s=(4.0_wp*z+1.0_wp),markColor='blue')
        call ticks()
        call labels('x','y','')
        call subplot(2,2,4)
        call xylim([0.0_wp,1.0_wp],[0.0_wp,1.0_wp])
        call scatter(x,y,c=z,s=(4.0_wp*z+1.0_wp))
        call ticks()
        call labels('x','y','')
    end subroutine doScatter
Call graph
doscatter calls xylim, ticks, scatter, labels, subplot, figure
xylim calls plwind
ticks calls plbox
scatter calls plschr, plcol1, plssym, plptex, mixval
labels calls pllab
subplot calls plvpor, plvsta, plvasp, plssub, pladv
figure calls plssub, pladv, pleop, plbop
doexamples calls doscatter
main_prg calls doexamples