doSurface – PlPlotLib
doSurface Subroutine
Source File
Variables
N x y z i j
Source Code
doSurface
All Procedures
bar barh binData box colorbar colorbar2 colorize contour contourf doBar doContour doError doExamples doFillBetween doHist doLegend doPlot doQuiver doScatter doSurface endsWith errorbar figure fillBetween fillBetweenx flatten hist int2char labels legend linspace makeLogo mean meshGridX meshGridY mixval plot plot3 printTypes quiver randomNormal randomUniform real2char scatter setup show showProgress span startsWith stdev subplot surface ticks title wireframe xlabel xlim xticks xylim xyzlim ylabel ylim yticks
public subroutine doSurface()
Arguments
None
Description
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer, public, parameter :: N = 24
real(kind=wp), public, dimension(N) :: x
real(kind=wp), public, dimension(N) :: y
real(kind=wp), public, dimension(N,N) :: z
integer, public :: i
integer, public :: j
Source Code
    subroutine doSurface
        !! ![surface](|media|/example-9.svg)
        integer,parameter::N = 24
        real(wp),dimension(N)::x,y
        real(wp),dimension(N,N)::z
        integer::i,j
        x = linspace(-10.0_wp,10.0_wp,N)
        y = linspace(-10.0_wp,10.0_wp,N)
        forall(i=1:N,j=1:N)
            z(i,j) = sin( sqrt(x(i)**2+y(j)**2) )/sqrt(x(i)**2+y(j)**2)
        end forall
        call figure()
        call subplot(1,1,1,is3d=.true.)
        call xyzlim(mixval(x),mixval(y),mixval(z),zoom=1.1_wp)
        call surface(x,y,z,11)
!~         call wireframe(x,y,z,lineColor='k')
        call box('x','y','z')
    end subroutine doSurface
Call graph
dosurface calls xyzlim, linspace, mixval, surface, subplot, figure, box
xyzlim calls plwind, plw3d
surface calls linspace, plsurf3d
subplot calls plvpor, plvsta, plvasp, plssub, pladv
figure calls plssub, pladv, pleop, plbop
box calls plbox3
doexamples calls dosurface
main_prg calls doexamples