figure – PlPlotLib
figure Subroutine
Source File
Variables
isFirst
Source Code
figure
All Procedures
bar barh binData box colorbar colorbar2 colorize contour contourf doBar doContour doError doExamples doFillBetween doHist doLegend doPlot doQuiver doScatter doSurface endsWith errorbar figure fillBetween fillBetweenx flatten hist int2char labels legend linspace makeLogo mean meshGridX meshGridY mixval plot plot3 printTypes quiver randomNormal randomUniform real2char scatter setup show showProgress span startsWith stdev subplot surface ticks title wireframe xlabel xlim xticks xylim xyzlim ylabel ylim yticks
public subroutine figure()
Arguments
None
Description
Create a new figure
Calls
Called By
Variables
Type Visibility Attributes Name Initial
logical, public, save :: isFirst = .true.
Source Code
    subroutine figure
        !! Create a new figure
        logical,save::isFirst = .true.
        if(.not.isFirst) then
            call pleop()
        else
            isFirst = .false.
        end if
        call plbop()
        call plssub(1,1)
        call pladv(1)
        call resetPen()
    end subroutine figure
Call graph
figure calls pladv, pleop, plssub, plbop
doerror calls figure
doplot calls figure
basic_prg calls figure
doscatter calls figure
dosurface calls figure
makelogo calls figure
docontour calls figure
dohist calls figure
dobar calls figure
dolegend calls figure
doquiver calls figure
dofillbetween calls figure
doexamples calls doerror, doplot, doscatter, dosurface, docontour, dohist, dobar, dolegend, doquiver, dofillbetween
main_prg calls doexamples