labels – PlPlotLib
labels Subroutine
Source File
Source Code
labels
All Procedures
bar barh binData box colorbar colorbar2 colorize contour contourf doBar doContour doError doExamples doFillBetween doHist doLegend doPlot doQuiver doScatter doSurface endsWith errorbar figure fillBetween fillBetweenx flatten hist int2char labels legend linspace makeLogo mean meshGridX meshGridY mixval plot plot3 printTypes quiver randomNormal randomUniform real2char scatter setup show showProgress span startsWith stdev subplot surface ticks title wireframe xlabel xlim xticks xylim xyzlim ylabel ylim yticks
public subroutine labels(xLabel, yLabel, plotLabel, color)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: xLabel
Label for x-axis
character(len=*), intent(in) :: yLabel
Label for x-axis
character(len=*), intent(in) :: plotLabel
Label entire plot
character(len=*), intent(in), optional :: color
Color of labels
Description
Set x,y and plot labels
Calls
Called By
Source Code
    subroutine labels(xLabel,yLabel,plotLabel,color)
        !! Set x,y and plot labels
        character(*),intent(in)::xLabel
            !! Label for x-axis
        character(*),intent(in)::yLabel
            !! Label for x-axis
        character(*),intent(in)::plotLabel
            !! Label entire plot
        character(*),intent(in),optional::color
            !! Color of labels
        if(present(color)) call setColor(color)
        call pllab(xLabel,yLabel,plotLabel)
        call resetPen()
    end subroutine labels
Call graph
labels calls pllab
doerror calls labels
basic_prg calls labels
doscatter calls labels
makelogo calls labels
docontour calls labels
dobar calls labels
dolegend calls labels
doquiver calls labels
dofillbetween calls labels
doexamples calls doerror, doscatter, docontour, dobar, dolegend, doquiver, dofillbetween
main_prg calls doexamples