linspace – PlPlotLib
linspace Function
Source File
Variables
Nl i
Source Code
linspace
All Procedures
bar barh binData box colorbar colorbar2 colorize contour contourf doBar doContour doError doExamples doFillBetween doHist doLegend doPlot doQuiver doScatter doSurface endsWith errorbar figure fillBetween fillBetweenx flatten hist int2char labels legend linspace makeLogo mean meshGridX meshGridY mixval plot plot3 printTypes quiver randomNormal randomUniform real2char scatter setup show showProgress span startsWith stdev subplot surface ticks title wireframe xlabel xlim xticks xylim xyzlim ylabel ylim yticks
public function linspace(l, h, N) result(o)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: l
Low-bound for values
real(kind=wp), intent(in) :: h
High-bound for values
integer, intent(in), optional :: N
Number of values (default 20)
Return Value real(kind=wp), dimension(:),allocatable
Description
Return an array of evenly-spaced values
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: Nl
integer, public :: i
Source Code
    function linspace(l,h,N) result(o)
        !! Return an array of evenly-spaced values
        real(wp),intent(in)::l
            !! Low-bound for values
        real(wp),intent(in)::h
            !! High-bound for values
        integer,intent(in),optional::N
            !! Number of values (default 20)
        real(wp),dimension(:),allocatable::o
        integer::Nl,i
        Nl = 20
        if(present(N)) Nl = N
        o = [( (h-l)*real(i-1,wp)/real(Nl-1,wp)+l , i=1 , Nl )]
    end function linspace
Call graph
doerror calls linspace
doplot calls linspace
basic_prg calls linspace
dofillbetween calls linspace
dosurface calls linspace, surface
makelogo calls linspace
docontour calls linspace, contourf
surface calls linspace
dobar calls linspace
doquiver calls linspace
contourf calls linspace
dolegend calls linspace
bindata calls linspace
doexamples calls doerror, doplot, dofillbetween, dosurface, docontour, dobar, doquiver, dolegend, dohist
main_prg calls doexamples
dohist calls bindata, hist
hist calls bindata