makeLogo – PlPlotLib
makeLogo Subroutine
Source File
Variables
x y1 y2 y3
Source Code
makeLogo
All Procedures
bar barh binData box colorbar colorbar2 colorize contour contourf doBar doContour doError doExamples doFillBetween doHist doLegend doPlot doQuiver doScatter doSurface endsWith errorbar figure fillBetween fillBetweenx flatten hist int2char labels legend linspace makeLogo mean meshGridX meshGridY mixval plot plot3 printTypes quiver randomNormal randomUniform real2char scatter setup show showProgress span startsWith stdev subplot surface ticks title wireframe xlabel xlim xticks xylim xyzlim ylabel ylim yticks
public subroutine makeLogo()
Arguments
None
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=wp), public, dimension(:), allocatable :: x
real(kind=wp), public, dimension(:), allocatable :: y1
real(kind=wp), public, dimension(:), allocatable :: y2
real(kind=wp), public, dimension(:), allocatable :: y3
Source Code
    subroutine makeLogo
        real(wp),dimension(:),allocatable::x,y1,y2,y3
        x  = linspace(0.0_wp,1.0_wp,100)
        y1 = x**2-1.0_wp
        y2 = 2.0_wp*x-1.0_wp
        y3 = x
        y3 = cos(2.0_wp*PI*x)
        call figure()
        call subplot(1,1,1)
        call xylim(mixval(x),mixval([y1,y2,y3])*1.1_wp)
        call plot(x,y1,lineColor='b',lineWidth=10.0_wp)
        call plot(x,y2,lineColor='r',lineWidth=10.0_wp)
        call plot(x,y3,lineColor='c',lineWidth=10.0_wp)
        call ticks(lineWidth=5.0_wp)
        call labels('','','')
    end subroutine makeLogo
Call graph
makelogo calls linspace, mixval, xylim, plot, labels, subplot, figure, ticks
xylim calls plwind
plot calls plptex, plline, plssym
labels calls pllab
subplot calls plvpor, plvsta, plvasp, plssub, pladv
figure calls plssub, pladv, pleop, plbop
ticks calls plbox