startsWith – PlPlotLib
startsWith Function
Source File
public function startsWith(text, str) result(o)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: text
Text to search
character(len=*), intent(in) :: str
String to look for
Return Value logical
Description
Test if text starts with str
Called By
Variables
Type Visibility Attributes Name Initial
integer, public :: k
Source Code
    function startsWith(text,str) result(o)
        !! Test if text starts with str
        character(*),intent(in)::text
            !! Text to search
        character(*),intent(in)::str
            !! String to look for
        logical::o
        integer::k
        k = len(str)
        o = text(1:k)==str
    end function startsWith
Call graph
legend calls dolegendbox
dolegend calls legend
examples_prg calls dolegend