xylim – PlPlotLib
xylim Subroutine
Source File
Variables
xbl ybl
Source Code
xylim
All Procedures
bar barh binData box colorbar colorbar2 colorize contour contourf doBar doContour doError doExamples doFillBetween doHist doLegend doPlot doQuiver doScatter doSurface endsWith errorbar figure fillBetween fillBetweenx flatten hist int2char labels legend linspace makeLogo mean meshGridX meshGridY mixval plot plot3 printTypes quiver randomNormal randomUniform real2char scatter setup show showProgress span startsWith stdev subplot surface ticks title wireframe xlabel xlim xticks xylim xyzlim ylabel ylim yticks
public subroutine xylim(xb, yb)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(2) :: xb
x-range of plot
real(kind=wp), intent(in), dimension(2) :: yb
y-range of plot
Description
Set the x and y ranges of the plot
Calls
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=pp), public, dimension(2) :: xbl
real(kind=pp), public, dimension(2) :: ybl
Source Code
    subroutine xylim(xb,yb)
        !! Set the x and y ranges of the plot
        real(wp),dimension(2),intent(in)::xb
            !! x-range of plot
        real(wp),dimension(2),intent(in)::yb
            !! y-range of plot
        real(pp),dimension(2)::xbl,ybl
        xbl = localize(xb)
        ybl = localize(yb)
        call plwind(xbl(1),xbl(2),ybl(1),ybl(2))
    end subroutine xylim
Call graph
xylim calls plwind
doerror calls xylim
doplot calls xylim
basic_prg calls xylim
doscatter calls xylim
makelogo calls xylim
docontour calls xylim
dohist calls xylim
dobar calls xylim
dolegend calls xylim
doquiver calls xylim
dofillbetween calls xylim
doexamples calls doerror, doplot, doscatter, docontour, dohist, dobar, dolegend, doquiver, dofillbetween
main_prg calls doexamples