xyzlim – PlPlotLib
xyzlim Subroutine
Source File
public subroutine xyzlim(xb, yb, zb, altitude, azimuth, zoom)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(2) :: xb
x-range of plot
real(kind=wp), intent(in), dimension(2) :: yb
y-range of plot
real(kind=wp), intent(in), dimension(2) :: zb
z-range of plot
real(kind=wp), intent(in), optional :: altitude
Altitude angle of plot in degrees
real(kind=wp), intent(in), optional :: azimuth
Azimuth angle of plot in degrees
real(kind=wp), intent(in), optional :: zoom
Zoom ratio (default 1.0)
Description
Set the limits for a 3d plot
Calls
Called By
Variables
Type Visibility Attributes Name Initial
real(kind=pp), public :: al
real(kind=pp), public :: az
real(kind=pp), public :: zm
Source Code
    subroutine xyzlim(xb,yb,zb,altitude,azimuth,zoom)
        !! Set the limits for a 3d plot
        real(wp),dimension(2),intent(in)::xb
            !! x-range of plot
        real(wp),dimension(2),intent(in)::yb
            !! y-range of plot
        real(wp),dimension(2),intent(in)::zb
            !! z-range of plot
        real(wp),intent(in),optional::altitude
            !! Altitude angle of plot in degrees
        real(wp),intent(in),optional::azimuth
            !! Azimuth angle of plot in degrees
        real(wp),intent(in),optional::zoom
            !! Zoom ratio (default 1.0)
        real(pp)::al,az,zm
        al = 45.0_pp
        if(present(altitude)) al = real(altitude,pp)
        az = 60.0_pp
        if(present(azimuth)) az = real(azimuth,pp)
        zm = 1.0_pp
        if(present(zoom)) zm = real(zoom,pp)
        call plwind(-1.0_pp,1.0_pp,-1.0_pp,1.5_pp)
        call plw3d(zm,zm,1.2_pp*zm, &
        & real(xb(1),pp),real(xb(2),pp), &
        & real(yb(1),pp),real(yb(2),pp), &
        & real(zb(1),pp),real(zb(2),pp),al,az)
    end subroutine xyzlim
Call graph
xyzlim calls plw3d, plwind
dosurface calls xyzlim
examples_prg calls dosurface