mixval – PlPlotLib
mixval Interface
Source File
Module Procedures
mixval_1 mixval_2 mixval_3
All Procedures
bar barh binData box colorbar colorbar2 colorize contour contourf doBar doContour doError doExamples doFillBetween doHist doLegend doPlot doQuiver doScatter doSurface endsWith errorbar figure fillBetween fillBetweenx flatten hist int2char labels legend linspace makeLogo mean meshGridX meshGridY mixval plot plot3 printTypes quiver randomNormal randomUniform real2char scatter setup show showProgress span startsWith stdev subplot surface ticks title wireframe xlabel xlim xticks xylim xyzlim ylabel ylim yticks
public interface mixval
Return a 2-vector comprising the minimum and maximum values of an array
Called By
Module Procedures
private function mixval_1(x) result(b)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
Array to find extrema in
Return Value real(kind=wp), dimension(2)
Description
Return [hi,low] for an array
private function mixval_2(x) result(b)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:) :: x
Array to find extrema in
Return Value real(kind=wp), dimension(2)
Description
Return [hi,low] for an array
private function mixval_3(x) result(b)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:,:,:) :: x
Array to find extrema in
Return Value real(kind=wp), dimension(2)
Description
Return [hi,low] for an array
Call graph
doerror calls mixval
doplot calls mixval
basic_prg calls mixval
dofillbetween calls mixval
dohist calls mixval, bar, hist
quiver calls mixval
makelogo calls mixval
docontour calls mixval
bar calls mixval
scatter calls mixval
dobar calls mixval, bar, barh
dolegend calls mixval
doquiver calls mixval, quiver
dosurface calls mixval
barh calls mixval
hist calls mixval, bar
doexamples calls doerror, doplot, dofillbetween, dohist, docontour, dobar, dolegend, doquiver, dosurface, doscatter
main_prg calls doexamples
doscatter calls scatter