main_prg – PlPlotLib
main_prg Program
Source File
Source Code
main_prg
All Programs
basic_prg main_prg
Uses:
kinds_mod
plplotlib_mod
examples_mod
Calls
Source Code
program main_prg
    use kinds_mod
    use plplotlib_mod
    use examples_mod
    implicit none
    call setup(whiteOnBlack=.false.)
!~     call setup(device='svgqt',fileName='examples/example-%n.svg',figSize=[320,240],transparent=.true.)
!~     call setup(device='svgqt',fileName='examples/logo-%n.svg',figSize=[500,500])
!~     call setup(device='svgqt',filename='examples/example-%n.svg',transparent=.true.)
    call doExamples()
!~     call makeLogo
    call show()
end program main_prg
Call graph
main_prg calls setup, show, doexamples
setup calls plsfnam, plsdev, plsfam, plsetopt, plinit, plfontld
show calls plend
doexamples calls doerror, doplot, doscatter, dolegend, docontour, dohist, dobar, dosurface, doquiver, dofillbetween
doerror calls linspace, mixval, xylim, plot, figure, subplot, errorbar, ticks, labels
doplot calls linspace, mixval, xylim, plot, figure, subplot, xlabel, ylabel, xticks, yticks, title
doscatter calls xylim, figure, subplot, ticks, labels, scatter
dolegend calls linspace, mixval, xylim, plot, figure, subplot, ticks, labels, legend
docontour calls linspace, mixval, xylim, figure, subplot, ticks, labels, contour, colorbar, contourf
dohist calls mixval, xylim, figure, subplot, ticks, bindata, hist, bar
dobar calls linspace, mixval, xylim, figure, subplot, ticks, labels, bar, barh
dosurface calls linspace, mixval, figure, subplot, xyzlim, surface, box
doquiver calls linspace, mixval, xylim, figure, subplot, ticks, labels, colorbar, quiver
dofillbetween calls linspace, mixval, xylim, plot, figure, subplot, ticks, labels, fillbetween
xylim calls plwind
plot calls plptex, plline, plssym
figure calls pladv, pleop, plssub, plbop
subplot calls pladv, plssub, plvpor, plvsta, plvasp
errorbar calls plerrx, plerry
ticks calls plbox
labels calls pllab
xlabel calls plmtex
ylabel calls plmtex
xticks calls plbox
yticks calls plbox
title calls plmtex
scatter calls mixval, plptex, plssym, plschr, plcol1
legend calls pllegend, domarkers, doboxes, dolegendbox, dolines, dotext
contour calls plcont
colorbar calls plcolorbar
contourf calls linspace, plshades
bindata calls linspace
hist calls mixval, bindata, bar
bar calls mixval, plline, plcol1, plfill
barh calls mixval, plline, plcol1, plfill
xyzlim calls plwind, plw3d
surface calls linspace, plsurf3d
box calls plbox3
quiver calls mixval, plcol1, plvect
fillbetween calls plfill